name: Build and sign WebExtension
author: Fabian Große
description: Builds and signs your WebExtension using Mozilla's web-ext tool.
branding:
  icon: upload
  color: orange

inputs:
  web-ext-source-dir:
    description: Directory where the manifest.json is located.
    required: false
    default: "."

  web-ext-target-dir:
    description: Output signed file to this directory.
    required: false
    default: "."

  amo-api-key:
    description: Your key for Mozilla's API
    required: true

  amo-api-secret:
    description: Your secret for Mozilla's API
    required: true

  web-ext-id:
    description: UUID of your existing extension. Signing new extensions is not supported.
    required: true

  sign-listed:
    description: Set to 'true' to list the extension on AMO. Defaults to 'false' for unlisted signing.
    required: true
    default: false

runs:
  using: docker
  image: Dockerfile
  env:
    WEB_EXT_SOURCE_DIR: ${{ inputs. web-ext-source-dir }}
    WEB_EXT_TARGET_DIR: ${{ inputs. web-ext-target-dir }}
    WEB_EXT_API_KEY: ${{ inputs.amo-api-key }}
    WEB_EXT_API_SECRET: ${{ inputs.amo-api-secret }}
    WEB_EXT_ID: ${{ inputs.web-ext-id }}
    SIGN_LISTED: ${{ inputs.sign-listed }}
